version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment: 
      POSTGRES_PASSWORD: postgres_password
    ports: 
      - 5432:5432
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # volumes: 
      # - /app/node_modules
      # - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    # volumes:
      # - /app/node_modules
      # - ./client:/app
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379      
    # volumes:
      # - /app/node_modules
      # - ./worker:/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '80:80'